# Where things are
destination:  ./site
data_dir:     ./_data
collections:  null

# Exclude DIR
exclude: [/less]

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      Australia/Melbourne

# Site Meta
url: http://unihack.net
og_image: /img/unihack-og.jpg
description: "UNIHACK is Australia's premier student hackathon, based in Melbourne and Sydney. Students get 24 hours to design and build something awesome – an app, website, piece of hardware... anything goes. Solve a problem, impress us and win some prizes!"
